// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvL3LnPraGDwSc7Y3WjdA76GAAxbkKUq8',
    appId: '1:184476298837:web:43102c42017d7f1f8deedc',
    messagingSenderId: '184476298837',
    projectId: 'sebratel-hub',
    authDomain: 'sebratel-hub.firebaseapp.com',
    storageBucket: 'sebratel-hub.firebasestorage.app',
    measurementId: 'G-T9Q1VW5PY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsUKtkL7mAjYUuR7qw3r1D5CxDgDBsu7g',
    appId: '1:184476298837:android:c5147e94af6b24988deedc',
    messagingSenderId: '184476298837',
    projectId: 'sebratel-hub',
    storageBucket: 'sebratel-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-dF5nGOaD7FInLhQwxufS24POFxFOrCA',
    appId: '1:184476298837:ios:c51124179268a31f8deedc',
    messagingSenderId: '184476298837',
    projectId: 'sebratel-hub',
    storageBucket: 'sebratel-hub.firebasestorage.app',
    androidClientId: '184476298837-tu2lj33na2qvd9e0uek9rfgd5hf3oesn.apps.googleusercontent.com',
    iosClientId: '184476298837-mamgh8rdaa06tlghpkttni37costh4jk.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.CounterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvL3LnPraGDwSc7Y3WjdA76GAAxbkKUq8',
    appId: '1:184476298837:web:43102c42017d7f1f8deedc',
    messagingSenderId: '184476298837',
    projectId: 'sebratel-hub',
    authDomain: 'sebratel-hub.firebaseapp.com',
    storageBucket: 'sebratel-hub.firebasestorage.app',
    measurementId: 'G-T9Q1VW5PY8',
  );
}
